---
- name: Make sure the necessary packages are installed
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - wpasupplicant
    - python-pip
  when: wpa_passphrase | bool

- name: Make sure pexpect is installed (for the expect module)
  pip:
    name: pexpect
    state: present
    extra_args: --user
  when: wpa_passphrase | bool

- name: Generate encrypted passphrases
  expect:
    command: wpa_passphrase {{ item.ssid }}
    responses:
      "# reading passphrase": "{{ item.psk }}"
  when: item.psk is defined and wpa_passphrase | bool
  with_items: "{{ wpa_networks }}"
  register: wpa_encrypted_networks
  changed_when: false

- name: Generate wpa_supplicant.conf
  become: yes
  template:
    src: templates/etc/wpa_supplicant/wpa_supplicant.conf.j2
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    owner: root
    group: root
    mode: 0600
  notify: reconfigure wpa
